on:
  push:

jobs:
  build:
    name: macOS Build
    runs-on: macOS-latest
    steps:
      - name: Force xcode 11
        run: sudo xcode-select -switch /Applications/Xcode_11.1.app

      - uses: actions/checkout@v1

      - name: Prepare certificates and keys
        env:
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        run: |
          cd certificates
          ./load-certificates.sh

      - name: Dependencies
        run: |
          cd VelocitekControlCenter
          carthage bootstrap --no-use-binaries --platform mac --cache-builds

      - name: build
        run: |
	  xcodebuild -project "VelocitekControlCenter/Velocitek Control Center.xcodeproj" -scheme 'Velocitek Control Center' build

      # - name: Package DMG
      #   run: |
      #     make dmg

          #- name: Package for AppStore
          # run: |
          # make appstore

      - name: publish build artifacts back to GitHub
        uses: actions/upload-artifact@master
        with:
          name: VelocitekControlCenter
          path: distribution/
